ipv6..., spoof, srv_keepalive

diff --git a/mempo-firewallsh b/mempo-firewallsh
--- a/mempo-firewallsh
+++ b/mempo-firewallsh
@@ -1,7 +1,7 @@
-!/bin/bash -e
+#!/bin/bash -e
 
 # simple firewall version 2.x (possibly with edited local configuration here)
-# author: maintained by: rfree - github.com/rfree/
+# author: maintained by: rfree - github.com/rfree/ + github.com/rfree2/
 
 # base code by:
 # by tuxguy - freenet/fms Identity: SSK@lRke4fhCLOHbCn-D0~1dKBPVg08oLB5K-avTEkWWmjg,jB6oKGWv07-5RuDHletDPIJbiLDSbOShvPnClFw4EdY,AQACAAE/
@@ -9,9 +9,8 @@
 # freenet site (freesite, use freenetproject.org software to access it) is located on URL:
 # freenet:USK@LdlyLrarSH~gin8K5iJcsPagkq33ICMyfO1jysGH4DA,Q22eGrV5MVWCE123WY3LJ4e7CIX1lt1kw6N2Fe~ir88,AQACAAE/tuxguy/-1/#firewall-1
 
-
 # READ THIS WARNING:
-# Before using this script - do search/grep for "configure" and "scret".  Also before sharing/posting improvments to this post remove such data.
+# Before using this script - do search/grep for "configure" and "secret".  Also before sharing/posting improvments to this post remove such data.
 # Review entire script yourself it will run as root.
 # Tie this script into init.d or similar autostart mechanism later.
 
@@ -67,8 +66,9 @@
 # PROT_in  - any access *into* protected-service is blocked (so probably ext->lo, because lo->lo is allowed if not stopped by _out)
 #
 
-echo "Starting firewall"
+# scripts
 
+echo "Loading the firewall"
 
 # === the STATIC PART (library?) ==================================================================
 
@@ -77,9 +77,21 @@ function iptab() {
 	printf "  iptables: %s\n" "$*"
 	iptables $* || { echo "ERROR while doing: iptables $*" ; echo "STOP because the error." ; exit 1 ; }
 }
+function iptab6() {
+	printf "  iptables: %s\n" "$*"
+	ip6tables $* || { echo "ERROR while doing: iptables $*" ; echo "STOP because the error." ; exit 1 ; }
+}
 function iptab_hidden() {
 	printf "  iptables: (hidden rule) \n" 
 	iptables $* || { 
+		echo "ERROR while doing: iptables (hidden rule - edit iptab_hidden to see hidden rules on error)" ; 
+		printf "iptables ERROR was on: %s\n" "$*"  # <--- XXX temporarly uncomment this to see what caused error
+		echo "STOP because the error." ; exit 1 ; 
+	}
+}
+function iptab6_hidden() {
+	printf "  ip6tables: (hidden rule) \n" 
+	ip6tables $* || { 
 		echo "ERROR while doing: iptables (hidden rule - edit iptab_hidden to see hidden rules on error)" ; 
 		printf "iptables ERROR was on: %s\n" "$*"  # <--- XXX temporarly uncomment this to see what caused error
 		echo "STOP because the error." ; exit 1 ; 
@@ -90,26 +102,34 @@ function block_everything() {
 	iptab -A INPUT   -j DROP
 	iptab -A OUTPUT  -j DROP
 	iptab -A FORWARD -j DROP
+	iptab6 -A INPUT   -j DROP
+	iptab6 -A OUTPUT  -j DROP
+	iptab6 -A FORWARD -j DROP
 }
 
 function block_everything_undo() {
 	iptab -D INPUT   -j DROP
 	iptab -D OUTPUT  -j DROP
 	iptab -D FORWARD -j DROP
+	iptab6 -D INPUT   -j DROP
+	iptab6 -D OUTPUT  -j DROP
+	iptab6 -D FORWARD -j DROP
 }
 
 function clear_firewall() {
-	for tab in filter mangle nat raw 
+	for tab in filter mangle raw nat
 	do
 		iptab  -t $tab  -F
 		iptab  -t $tab  -X
 		iptab  -t $tab  -Z
 	done
 
-# temporary polices while loading.
-	iptab  -P INPUT     DROP
-	iptab  -P OUTPUT    DROP
-	iptab  -P FORWARD   DROP
+	for tab in filter mangle raw 
+	do
+		iptab6  -t $tab  -F
+		iptab6  -t $tab  -X
+		iptab6  -t $tab  -Z
+	done
 }
 
 
@@ -117,7 +137,6 @@ function _add_log() {
 	chain=$1
 	normal=$2 ; normalB=$3; 	Elog="2/hour"   ; ElogB=1;  # normal speed/bucket (from $1 $2) and alert-about-over-logging speed/bucket
 	flag=0x8000 # flag used to mark the branch that the packet is *NOT* logged too fast (if THIS $chain logging is used too fast)
-
 	iptab -A $chain  -m limit  --limit "$normal" --limit-burst "$normalB"   -j MARK --or-mark 0x8000   # mark
 	# say if it was too fast (but limit this allerting too):
 	iptab -A $chain  -m mark  ! --mark 0x8000/0x8000  -m limit --limit  "$Elog" --limit-burst "$ElogB"  -j LOG --log-prefix "fwSPAM_$chain: " --log-ip-options --log-tcp-options --log-uid
@@ -197,8 +216,15 @@ function make_ok_slow() {
 
 # *EDIT* configure me:  
 tor_html_proxy_port=8118       # configure. secret? TCP port on localhost used for isolated user HTTP. Eg 8118 privoxy. Remember to set privoxy to use TOR parent!!!
-lan_ip_mask="192.168.0.0/24"  # configure. secret? IP/mask of the LAN e.g. for allowing certain freenet nodes to go only to LAN (secret?)
+tor_socks_port=9050 # the TOR socks port, usually 90050
 
+# your network - configure this if needed (e.g. make the rules more tight)
+lan_ip_mask="192.168.0.0/24"  # configure. secret? IP/mask of the primary LAN e.g. for allowing certain freenet nodes to go only to LAN (secret?)
+net_allow_ip_for_eth="192.168.0.0/16" # ip/mask that are allowed to come from eth+
+net_allow_ip_for_usb="192.168.0.0/16"
+net_allow_ip_for_wlan="192.168.0.0/16"
+net_allow_ip_for_tun0="10.0.0.0/8"
+net_allow_ip_for_tun1="10.0.0.0/8"
 
 # TODO use this lists/make them real lists/arrays in bash
 # TODO this lists are NOT USED in this version of script, instead edit stuff below directly.
@@ -221,39 +247,39 @@ freenet_ports_nttp="8888:8899" #  Ports :TODO(not used now, edit below instead)
 yacy_uid="" # Which unix-user(s) like "srv_yact" ir 1003 will run the YACY server
 
 # lists are separated by space
-clients_freenet="rafal" #  TODO List of unix users that should generally use Freenet (connect to fproxy :8888, FMS etc) e.g. srv_fn_cli
+clients_freenet="rafal srv_keepalive" #  TODO List of unix users that should generally use Freenet (connect to fproxy :8888, FMS etc) e.g. srv_fn_cli
 clients_yact="" # TODO List of unix users that should generally use YACY (connect to web interface of Yacy :8090 etc) srv_yacy_cli
-users_tor_only="" # List of unix users that will be isolated to only user TOR (or TOR http proxy like privoxy, CONFIGURE it to use TOR!)
-users_no_network="" # List of unix users that will not be allowed to use any network
+users_tor_only="" # isolated: List of unix users that will be isolated to only user TOR (or TOR http proxy like privoxy, CONFIGURE it to use TOR!)
+users_no_network="" # isolated: List of unix users that will not be allowed to use any network
 clients_user="rafal" # list of users that can access local secure services
-clients_user_locked="" # list of users that should access ONLY use local secure services
+clients_user_locked="" # isolated: list of users that should access ONLY use local secure services
 
 clear_firewall # <--- ! 
 
 block_everything # <--- !
 
 # create general use targets:
-make_reject_after_log_speed "STOP"           "5/hour" "20"   # general
-make_reject_after_log_speed "STOP_all_o"     "5/hour" "20"   # unexpected outputs (not used probably)
-make_reject_after_log_speed "STOP_all_i"     "10/hour" "30"   # unexpected inputs (tune this down if directly interneted to avoid spam, esp if no NAT/firewall outside)
-make_reject_after_log_speed "STOP_invalid"   "5/hour" "20"
-make_reject_after_log_speed "STOP_invalid2"  "5/hour" "20"
-make_reject_after_log_speed "STOP_inspoof"  "5/hour" "20"
+make_reject_after_log_speed "STOP"           "2/hour" "5"   # general
+make_reject_after_log_speed "STOP_all_o"     "2/hour" "5"   # unexpected outputs (not used probably)
+make_reject_after_log_speed "STOP_all_i"     "1/hour" "3"  # unexpected inputs (tune this down if directly interneted to avoid spam, esp if no NAT/firewall outside)
 
-#####################################################################
-#####################################################################
-# basic rules
+# part_0100: basic rules
 
 # established connections - continue them without extra filtering
 iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
 iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
 
 # kill invalid
-iptables -A INPUT  -m state --state INVALID -j STOP_invalid
-iptables -A OUTPUT -m state --state INVALID -j STOP_invalid2
+make_reject_after_log_speed "STOP_invalidI"  "1/hour" "3"
+make_reject_after_log_speed "STOP_invalidO"  "5/hour" "1"
+make_reject_after_log_speed "STOP_invalidF"  "1/hour" "3"
+iptables -A INPUT   -m state --state INVALID -j STOP_invalidI
+iptables -A OUTPUT  -m state --state INVALID -j STOP_invalidO
+iptables -A FORWARD -m state --state INVALID -j STOP_invalidF
 
-# kill spoof
+# part_0150: basic spoof protection
 # configure this. secret (a bit?)
+make_reject_after_log_speed "STOP_inspoof"   "1/minute" "3" # this is important
 chain=VERIFY_inspoof
 	iptab -N $chain 
 	# configure. secret?  List what device can have what IP address. Read "man iptables" manual, or
@@ -264,10 +290,13 @@ chain=VERIFY_inspoof
 	 iptab -A $chain  -d 255.255.255.255 -j RETURN  # multicast to any
 
 	 iptab -A $chain  -i lo    -d 127.0.0.1/8  -j RETURN  # this always
-	 iptab -A $chain  -i lo    -d 192.168.0.0/16  -j RETURN  # this always... isnt there a better way? used when src==dst
+	 iptab -A $chain  -i lo    -d 192.168.0.0/16  -j RETURN  # this always... isnt there a better way? used when src==dst TODO
 
-	 iptab -A $chain  -i eth+  -d 192.168.0.0/24  -j RETURN # configure. secret? TODO
-	 iptab -A $chain  -i usb+  -d 192.168.0.0/24  -j RETURN # configure. secret? TODO
+	 iptab -A $chain  -i eth+   -d "$net_allow_ip_for_eth"  -j RETURN
+	 iptab -A $chain  -i usb+   -d "$net_allow_ip_for_usb"  -j RETURN
+	 iptab -A $chain  -i wlan+  -d "$net_allow_ip_for_wlan"  -j RETURN
+	 iptab -A $chain  -i tun0   -d "$net_allow_ip_for_wlan"  -j RETURN
+	 iptab -A $chain  -i tun1   -d "$net_allow_ip_for_wlan"  -j RETURN
 
 	iptab -A $chain -j STOP_inspoof # else (all not listed) is a spoof!
 # end
@@ -298,7 +327,7 @@ iptables -A INPUT  -j VERIFY_inspoof
 make_stop "only_TOR"
 for user in "$users_tor_only" ; do if [[ ! -z "$user" ]] ; then
 	iptab  -A OUTPUT  -m owner --uid-owner $user  -d 127.0.0.1/24  -p tcp --dport "$tor_html_proxy_port" -j ACCEPT # via proxy
-	iptab  -A OUTPUT  -m owner --uid-owner $user  -d 127.0.0.1/24  -p tcp --dport 9050 -j ACCEPT # directly tor
+	iptab  -A OUTPUT  -m owner --uid-owner $user  -d 127.0.0.1/24  -p tcp --dport "$tor_socks_port" -j ACCEPT # directly tor
 	iptab  -A OUTPUT  -m owner --uid-owner $user  -j S_only_TOR
 fi ; done
 
@@ -310,8 +339,10 @@ fi ; done
 #####################################################################
 #####################################################################
 
+# part
 echo "allow other services - EARLY"
-make_ok_fast "i2pirc" ; iptab  -A INPUT -i lo -p tcp --dport 6668 -j G_i2pirc
+make_ok_fast "i2pirc6668" ; iptab  -A INPUT -i lo -p tcp --dport 6668 -j G_i2pirc6668
+make_ok_fast "i2pirc6669" ; iptab  -A INPUT -i lo -p tcp --dport 6669 -j G_i2pirc6669
 
 #####################################################################
 #####################################################################
@@ -405,7 +436,8 @@ then # TODO disabled
 echo "CLIENTS allowed to talk to local darknet"
 # Freenet 
 # allow: ALL this users-clients to freenet/fms/nntp. Usually srv_fn_cli
-for user in "$clients_user" ; do if [[ ! -z "$user" ]] ; then
+for user in $clients_user $clients_freenet ; do if [[ ! -z "$user" ]] ; then
+	echo "USER $user"
 	iptab  -A OUTPUT -m owner --uid-owner $user  -d 127.0.0.1/24  -p tcp --dport 8888:8899 -j ACCEPT # FRED
 	iptab  -A OUTPUT -m owner --uid-owner $user  -d 127.0.0.1/24  -p tcp --dport 9481:9483 -j ACCEPT # FCP (for e.g. jSite?)
 	iptab  -A OUTPUT -m owner --uid-owner $user  -d 127.0.0.1/24  -p tcp --dport 8080:8089 -j ACCEPT # FMS
@@ -525,7 +557,5 @@ echo "Firewall ready, enabling"
 block_everything_undo # !
 
 echo "Firewall done."
-
-
 
 
